FROM node:alpine as builder
WORKDIR /frontend
COPY package.json .
RUN npm install
# 빌드 수행
COPY . .
RUN npm run build || exit 1

# 2단계: 빌드된 애플리케이션 실행
FROM node:20.10.0

# serve 설치
RUN npm install -g serve

# 5173 포트 노출
EXPOSE 5173

# npm start 스크립트 실행
CMD ["npm", "run", "dev"]: